apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
        - name: app
          image: ghcr.io/bartlomiejwo/gha-training:latest
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
      imagePullSecrets:
        - name: ghcr-secret
