name: CI

on:
  push:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: self-hosted
    outputs:
      short_sha: ${{ steps.sha.outputs.short_sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run tests
        env:
          PYTHONPATH: .
        run: pytest

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set short SHA
        id: sha
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:${{ steps.sha.outputs.short_sha }} .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:${{ steps.sha.outputs.short_sha }}

  deploy-dev:
    uses: ./.github/workflows/deploy-k8s.yml
    with:
      environment: dev
      namespace: dev
      values_file: fastapi-chart/values-dev.yaml
      short_sha: ${{ needs.build.outputs.short_sha }}
    needs: build
      
  deploy-staging:
    uses: ./.github/workflows/deploy-k8s.yml
    with:
      environment: staging
      namespace: staging
      values_file: fastapi-chart/values-staging.yaml
      short_sha: ${{ needs.build.outputs.short_sha }}
    needs: build

  deploy-prod:
    uses: ./.github/workflows/deploy-k8s.yml
    with:
      environment: prod
      namespace: prod
      values_file: fastapi-chart/values-prod.yaml
      short_sha: ${{ needs.deploy-staging.outputs.short_sha }}
    needs: deploy-staging
    

