name: build-and-deploy-dev

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: self-hosted
    outputs:
      short_sha: ${{ steps.sha.outputs.short_sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Python CI
        uses: ./.github/actions/python-ci

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set short SHA
        id: sha
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=1 docker build \
            --cache-to=type=inline \
            --cache-from=type=registry,ref=ghcr.io/${{ github.repository }}:buildcache \
            -t ghcr.io/${{ github.repository }}:${{ steps.sha.outputs.short_sha }} .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:${{ steps.sha.outputs.short_sha }}

  deploy-dev:
    uses: ./.github/workflows/deploy-k8s.yml
    with:
      environment: dev
      namespace: dev
      values_file: fastapi-chart/values-dev.yaml
      image_tag: ${{ needs.build.outputs.short_sha }}
    needs: build
    

