name: build-and-release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Python CI
        uses: ./.github/actions/python-ci

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=1 docker build \
            --cache-to=type=inline \
            --cache-from=type=registry,ref=ghcr.io/${{ github.repository }}:buildcache \
            -t ghcr.io/${{ github.repository }}:${{ github.ref_name }} .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}

  deploy-staging:
    uses: ./.github/workflows/deploy-k8s.yml
    with:
      environment: staging
      namespace: staging
      values_file: fastapi-chart/values-staging.yaml
      image_tag: ${{ github.ref_name }}
    needs: build

  deploy-prod:
    uses: ./.github/workflows/deploy-k8s.yml
    with:
      environment: prod
      namespace: prod
      values_file: fastapi-chart/values-prod.yaml
      image_tag: ${{ needs.deploy-staging.outputs.image_tag }}
    needs: deploy-staging
